name: ultralytics_yolo
description: A Flutter plugin for Ultralytics YOLO computer vision models
version: 0.0.3
homepage: https://github.com/ultralytics/ultralytics_yolo.git

environment:
  flutter: ">=3.19.0"
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  plugin:
    platforms:
      android:
        package: com.ultralytics.ultralytics_yolo
        pluginClass: UltralyticsYoloPlugin
      ios:
        pluginClass: UltralyticsYoloPlugin
